coeff2_4 = ...
-2*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^6*kplus^3 -6*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^5*kplus^3*lambda -6*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*lambda^2 ...
-2*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^3;
