vars = {-2*km^3*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*lambda^3 - 6*km^2*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus*lambda^3 - 
      6*km^2*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus*lambda^3 - 6*km*koff^2*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*
       lambda^3 - 12*km*koff*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^2*lambda^3 - 
      6*km*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^5*kplus^2*lambda^3 - 2*koff^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^3 - 
      6*koff^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*lambda^3 - 6*koff*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^5*kplus^3*lambda^3 - 
      2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^6*kplus^3*lambda^3 - 6*km^2*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*lambda^4 - 
      12*km*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus*lambda^4 - 12*km*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus*
       lambda^4 - 6*koff^2*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*lambda^4 - 
      12*koff*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^2*lambda^4 - 6*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^5*kplus^2*lambda^4 - 
      6*km*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*lambda^5 - 6*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus*lambda^5 - 
      6*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus*lambda^5 - 2*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*lambda^6 - 
      6*km^2*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus*lambda^3*PT - 3*km*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*
       lambda^3*PT - 3*km*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^2*lambda^3*PT + 
      3*koff^2*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^3*PT + 6*koff*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*
       lambda^3*PT + 3*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^5*kplus^3*lambda^3*PT - 
      6*km^2*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus*lambda^4*PT - 12*km*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus*lambda^4*
       PT - 3*km*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus^2*lambda^4*PT - 
      3*km*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*lambda^4*PT - 3*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*
       lambda^4*PT - 3*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^2*lambda^4*PT + 
      3*koff^2*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus^3*lambda^4*PT + 6*koff*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*
       lambda^4*PT + 3*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*lambda^4*PT - 
      12*km*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus*lambda^5*PT - 6*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus*lambda^5*PT - 
      3*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus^2*lambda^5*PT - 3*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*lambda^5*
       PT - 6*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus*lambda^6*PT - 6*km*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*lambda^3*
       PT^2 + 3*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^3*PT^2 + 
      3*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*lambda^3*PT^2 - 12*km*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus^2*lambda^4*
       PT^2 - 6*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*lambda^4*PT^2 + 6*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus^3*
       lambda^4*PT^2 + 6*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^4*PT^2 - 
      6*km*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))*kplus^2*lambda^5*PT^2 - 12*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus^2*lambda^5*
       PT^2 + 3*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))*kplus^3*lambda^5*PT^2 + 
      3*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus^3*lambda^5*PT^2 - 6*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))*kplus^2*lambda^6*PT^2 - 
      2*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^3*PT^3 - 6*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus^3*lambda^4*
       PT^3 - 6*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))*kplus^3*lambda^5*PT^3 - 2*kon^3*kplus^3*lambda^6*
       PT^3 - 6*km^2*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus*lambda^3*TT - 12*km*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*
       kplus^2*lambda^3*TT - 12*km*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^2*lambda^3*TT - 
      6*koff^2*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^3*TT - 12*koff*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*
       lambda^3*TT - 6*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^5*kplus^3*lambda^3*TT - 
      12*km*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus*lambda^4*TT - 12*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*
       lambda^4*TT - 12*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^2*lambda^4*TT - 
      6*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus*lambda^5*TT - 3*km*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*lambda^3*PT*
       TT + 6*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^3*PT*TT + 
      6*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*lambda^3*PT*TT - 3*km*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus^2*lambda^4*
       PT*TT - 3*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*lambda^4*PT*TT + 
      6*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus^3*lambda^4*PT*TT + 6*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*
       lambda^4*PT*TT - 3*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus^2*lambda^5*PT*TT + 
      3*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^3*PT^2*TT + 6*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus^3*lambda^4*
       PT^2*TT + 3*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))*kplus^3*lambda^5*PT^2*TT - 
      6*km*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*lambda^3*TT^2 - 6*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*
       lambda^3*TT^2 - 6*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*lambda^3*TT^2 - 
      6*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*lambda^4*TT^2 + 3*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^3*PT*
       TT^2 + 3*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus^3*lambda^4*PT*TT^2 - 
      2*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^3*TT^3, 3*km^2*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus*lambda^2 - 
      3*km*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^2*lambda^2 - 3*km*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^5*kplus^2*
       lambda^2 - 6*koff^2*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*lambda^2 - 
      12*koff*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^5*kplus^3*lambda^2 - 6*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^6*kplus^3*lambda^2 + 
      3*km^2*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus*lambda^3 + 6*km*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus*lambda^3 - 
      3*km*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*lambda^3 - 3*km*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^2*
       lambda^3 - 3*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^2*lambda^3 - 
      3*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^5*kplus^2*lambda^3 - 6*koff^2*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^3 - 
      12*koff*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*lambda^3 - 6*kon*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^5*kplus^3*lambda^3 + 
      6*km*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus*lambda^4 + 3*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus*lambda^4 - 
      3*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*lambda^4 - 3*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^2*lambda^4 + 
      3*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus*lambda^5 + 6*km*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^2*lambda^2*PT + 
      6*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*lambda^2*PT + 6*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^5*kplus^3*lambda^2*
       PT + 12*km*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*lambda^3*PT + 6*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^2*
       lambda^3*PT + 12*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^3*PT + 
      12*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*lambda^3*PT + 6*km*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus^2*lambda^4*
       PT + 12*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*lambda^4*PT + 6*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus^3*
       lambda^4*PT + 6*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^4*PT + 
      6*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus^2*lambda^5*PT + 3*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*lambda^2*PT^2 + 
      9*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^3*PT^2 + 9*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus^3*lambda^4*
       PT^2 + 3*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))*kplus^3*lambda^5*PT^2 + 6*km*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^2*
       lambda^2*TT - 3*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*lambda^2*TT - 
      3*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^5*kplus^3*lambda^2*TT + 6*km*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*lambda^3*
       TT + 6*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^2*lambda^3*TT - 3*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*
       lambda^3*TT - 3*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*lambda^3*TT + 
      6*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*lambda^4*TT - 12*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*lambda^2*PT*
       TT - 24*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^3*PT*TT - 12*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus^3*
       lambda^4*PT*TT + 3*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*lambda^2*TT^2 + 
      3*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^3*TT^2, 3*km*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^5*kplus^2*lambda - 
      6*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^5*kplus^3*lambda - 6*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^6*kplus^3*lambda + 
      6*km*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^2*lambda^2 + 3*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^5*kplus^2*lambda^2 - 
      12*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*lambda^2 - 12*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^5*kplus^3*lambda^2 + 
      3*km*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*lambda^3 + 6*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^2*lambda^3 - 
      6*koff*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^3 - 6*kon^2*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*lambda^3 + 
      3*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^2*lambda^4 + 3*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^5*kplus^3*lambda*PT + 
      9*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*lambda^2*PT + 9*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^3*PT + 
      3*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^2*kplus^3*lambda^4*PT + 3*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^5*kplus^3*lambda*TT + 
      6*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*lambda^2*TT + 3*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^3*TT, 
     -2*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^6*kplus^3 - 6*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^5*kplus^3*lambda - 
      6*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^4*kplus^3*lambda^2 - 2*kon^3*(kp * (kp / (koff + kp))^N * (1 - kp / (koff + kp)) / (1 + (kp / (koff + kp))^(N + 1)))^3*kplus^3*lambda^3}
