Emax = ...
    (PT*(YT* Delta *(gyp + (a* lambda *((koff/kon) + TT + ...
            (sqrt(-(a^2*gym*YT* Delta * lambda ^2* mu * ...
                 (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)* ...
                    mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta * ...
                     lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT* ...
                         Delta ) + 2*a*TT*(gpp*(gym + gyp) + gyp*YT* ...
                         Delta )* lambda  + a^2*TT*((koff/kon) + TT)*(gpp + ...
                       YT* Delta )* lambda ^2)* mu )^2)) - ...
              a* lambda * mu *(-(gpm*gym*YT* Delta * lambda * ...
                  (YT* Delta *(gyp + a*(koff/kon)* lambda ) + gpp*(gym + gyp + ...
                     a*(koff/kon)* lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )* ...
                 (gpp*(gym + gyp + a*TT* lambda )*(gym + gyp + a*((koff/kon) + TT)* ...
                      lambda ) + YT* Delta *(gym*(gyp + a*(koff/kon)* lambda ) + ...
                    (gyp + a*TT* lambda )*(gyp + a*((koff/kon) + TT)* lambda )))*...
                  mu ))/(a^2*(gpp + YT* Delta )* lambda ^2* mu *...
              (-(gpm*gym*YT* Delta * lambda ) + gpp*(gym + gyp + ...
                  a*TT* lambda )^2* mu  + YT* Delta *(gym*gyp + ...
                 (gyp + a*TT* lambda )^2)* mu )) - ...
            sqrt((-4*TT*(sqrt(-(a^2*gym*YT* Delta * lambda ^2* mu * ...
                    (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)* ...
                       mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta * ...
                        lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT* ...
                           Delta ) + 2*a*TT*(gpp*(gym + gyp) + gyp*YT* ...
                           Delta )* lambda  + a^2*TT*((koff/kon) + TT)*(gpp + ...
                          YT* Delta )* lambda ^2)* mu )^2)) - a* lambda * ...
                   mu *(-(gpm*gym*YT* Delta * lambda *(YT* Delta * ...
                       (gyp + a*(koff/kon)* lambda ) + gpp*(gym + gyp + a*(koff/kon)* ...
                          lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )* ...
                    (gpp*(gym + gyp + a*TT* lambda )*(gym + gyp + ... 
                       a*((koff/kon) + TT)* lambda ) + YT* Delta *(gym*(gyp + ...
                         a*(koff/kon)* lambda ) + (gyp + a*TT* lambda )*(gyp + ...
                         a*((koff/kon) + TT)* lambda )))* mu )))/(a^2* ...
                (gpp + YT* Delta )* lambda ^2* mu *(-(gpm*gym*YT* Delta * ...
                    lambda ) + gpp*(gym + gyp + a*TT* lambda )^2* mu  + ...
                 YT* Delta *(gym*gyp + (gyp + a*TT* lambda )^2)* mu )) +  ...
              ((koff/kon) + TT + (sqrt(-(a^2*gym*YT* Delta * lambda ^2* mu * ...
                     (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)* ...
                        mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta * ...
                         lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT* ...
                           Delta ) + 2*a*TT*(gpp*(gym + gyp) + gyp*YT* ...
                           Delta )* lambda  + a^2*TT*((koff/kon) + TT)*(gpp +  ...
                          YT* Delta )* lambda ^2)* mu )^2)) - a* lambda * ...
                    mu *(-(gpm*gym*YT* Delta * lambda *(YT* Delta * ...
                        (gyp + a*(koff/kon)* lambda ) + gpp*(gym + gyp + a*(koff/kon)* ...
                           lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )* ...
                     (gpp*(gym + gyp + a*TT* lambda )*(gym + gyp + ...
                        a*((koff/kon) + TT)* lambda ) + YT* Delta *(gym*(gyp + ...
                          a*(koff/kon)* lambda ) + (gyp + a*TT* lambda )*(gyp + ...
                          a*((koff/kon) + TT)* lambda )))* mu ))/(a^2*(gpp + ...
                   YT* Delta )* lambda ^2* mu *(-(gpm*gym*YT* Delta *...
                      lambda ) + gpp*(gym + gyp + a*TT* lambda )^2* mu  + ... 
                   YT* Delta *(gym*gyp + (gyp + a*TT* lambda )^2)* mu )))^ ...
               2)))/2) + gpp*(gym + gyp + ...
         (a* lambda *((koff/kon) + TT + (sqrt(-(a^2*gym*YT* Delta * lambda ^2* ...
                  mu *(-(gpm*(gpp + YT* Delta )* lambda ) + ...
                  gpp*(gym + gyp)* mu  + gyp*YT* Delta * mu )* ...
                 (gpm*gym*YT* Delta * lambda  - ((gym + gyp)* ...
                      (gpp*(gym + gyp) + gyp*YT* Delta ) + 2*a*TT* ...
                      (gpp*(gym + gyp) + gyp*YT* Delta )* lambda  + ...
                     a^2*TT*((koff/kon) + TT)*(gpp + YT* Delta )* lambda ^2)* mu )^...
                  2)) - a* lambda * mu *(-(gpm*gym*YT* Delta * lambda *...
                  (YT* Delta *(gyp + a*(koff/kon)* lambda ) + gpp*(gym + gyp + ...
                     a*(koff/kon)* lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )*...
                 (gpp*(gym + gyp + a*TT* lambda )*(gym + gyp + a*((koff/kon) + TT)*...
                      lambda ) + YT* Delta *(gym*(gyp + a*(koff/kon)* lambda ) + ...
                    (gyp + a*TT* lambda )*(gyp + a*((koff/kon) + TT)* lambda )))*...
                  mu ))/(a^2*(gpp + YT* Delta )* lambda ^2* mu * ...
              (-(gpm*gym*YT* Delta * lambda ) + gpp*(gym + gyp + ...
                  a*TT* lambda )^2* mu  + YT* Delta *(gym*gyp + ...
                 (gyp + a*TT* lambda )^2)* mu )) - ...
            sqrt((-4*TT*(sqrt(-(a^2*gym*YT* Delta * lambda ^2* mu * ...
                    (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)* ...
                       mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta * ...
                        lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT* ...
                           Delta ) + 2*a*TT*(gpp*(gym + gyp) + gyp*YT* ...
                           Delta )* lambda  + a^2*TT*((koff/kon) + TT)*(gpp + ...
                          YT* Delta )* lambda ^2)* mu )^2)) - a* lambda * ...
                   mu *(-(gpm*gym*YT* Delta * lambda *(YT* Delta * ...
                       (gyp + a*(koff/kon)* lambda ) + gpp*(gym + gyp + a*(koff/kon)*...
                          lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )*...
                    (gpp*(gym + gyp + a*TT* lambda )*(gym + gyp + ...
                       a*((koff/kon) + TT)* lambda ) + YT* Delta *(gym*(gyp + ...
                         a*(koff/kon)* lambda ) + (gyp + a*TT* lambda )*(gyp + ...
                         a*((koff/kon) + TT)* lambda )))* mu )))/(a^2*...
                (gpp + YT* Delta )* lambda ^2* mu *(-(gpm*gym*YT* Delta *...
                    lambda ) + gpp*(gym + gyp + a*TT* lambda )^2* mu  + ...
                 YT* Delta *(gym*gyp + (gyp + a*TT* lambda )^2)* mu )) + ...
              ((koff/kon) + TT + (sqrt(-(a^2*gym*YT* Delta * lambda ^2* mu *...
                     (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)*...
                        mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta *...
                         lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT*...
                           Delta ) + 2*a*TT*(gpp*(gym + gyp) + gyp*YT*...
                           Delta )* lambda  + a^2*TT*((koff/kon) + TT)*(gpp + ...
                          YT* Delta )* lambda ^2)* mu )^2)) - a* lambda *...
                    mu *(-(gpm*gym*YT* Delta * lambda *(YT* Delta *...
                        (gyp + a*(koff/kon)* lambda ) + gpp*(gym + gyp + a*(koff/kon)*...
                           lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )*...
                     (gpp*(gym + gyp + a*TT* lambda )*(gym + gyp + ...
                        a*((koff/kon) + TT)* lambda ) + YT* Delta *(gym*(gyp + ...
                          a*(koff/kon)* lambda ) + (gyp + a*TT* lambda )*(gyp + ...
                          a*((koff/kon) + TT)* lambda )))* mu ))/(a^2*(gpp + ...
                   YT* Delta )* lambda ^2* mu *(-(gpm*gym*YT* Delta *...
                      lambda ) + gpp*(gym + gyp + a*TT* lambda )^2* mu  + ...
                   YT* Delta *(gym*gyp + (gyp + a*TT* lambda )^2)* mu )))^...
               2)))/2)))/...
     (YT* Delta *(gyp + (a* lambda *((koff/kon) + TT + ...
           (sqrt(-(a^2*gym*YT* Delta * lambda ^2* mu * ...
                (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)*...
                   mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta *...
                    lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT*...
                        Delta ) + 2*a*TT*(gpp*(gym + gyp) + gyp*YT* Delta )*...
                      lambda  + a^2*TT*((koff/kon) + TT)*(gpp + YT* Delta )*...
                      lambda ^2)* mu )^2)) - a* lambda * mu *...
              (-(gpm*gym*YT* Delta * lambda *(YT* Delta *(gyp + ...
                    a*(koff/kon)* lambda ) + gpp*(gym + gyp + a*(koff/kon)* lambda ))) + ...
               (gpp*(gym + gyp) + gyp*YT* Delta )*(gpp*(gym + gyp + ...
                   a*TT* lambda )*(gym + gyp + a*((koff/kon) + TT)* lambda ) + ...
                 YT* Delta *(gym*(gyp + a*(koff/kon)* lambda ) + ...
                   (gyp + a*TT* lambda )*(gyp + a*((koff/kon) + TT)* lambda )))*...
                 mu ))/(a^2*(gpp + YT* Delta )* lambda ^2* mu *...
             (-(gpm*gym*YT* Delta * lambda ) + gpp*(gym + gyp + ...
                 a*TT* lambda )^2* mu  + YT* Delta *(gym*gyp + ...
                (gyp + a*TT* lambda )^2)* mu )) -... 
           sqrt((-4*TT*(sqrt(-(a^2*gym*YT* Delta * lambda ^2* mu *...
                   (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)*...
                      mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta *...
                       lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT*...
                           Delta ) + 2*a*TT*(gpp*(gym + gyp) + gyp*YT*...
                           Delta )* lambda  + a^2*TT*((koff/kon) + TT)*(gpp + ...
                         YT* Delta )* lambda ^2)* mu )^2)) - a* lambda *...
                  mu *(-(gpm*gym*YT* Delta * lambda *(YT* Delta *...
                      (gyp + a*(koff/kon)* lambda ) + gpp*(gym + gyp + a*(koff/kon)*...
                         lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )*...
                   (gpp*(gym + gyp + a*TT* lambda )*(gym + gyp + a*((koff/kon) + TT)*...
                        lambda ) + YT* Delta *(gym*(gyp + a*(koff/kon)* lambda ) + ...
                      (gyp + a*TT* lambda )*(gyp + a*((koff/kon) + TT)* lambda )))*...
                    mu )))/(a^2*(gpp + YT* Delta )* lambda ^2* mu *(...
                -(gpm*gym*YT* Delta * lambda ) + gpp*(gym + gyp + ...
                   a*TT* lambda )^2* mu  + YT* Delta *(gym*gyp + ...
                  (gyp + a*TT* lambda )^2)* mu )) + ...
             ((koff/kon) + TT + (sqrt(-(a^2*gym*YT* Delta * lambda ^2* mu *...
                    (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)*...
                       mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta *...
                        lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT*...
                           Delta ) + 2*a*TT*(gpp*(gym + gyp) + gyp*YT*...
                           Delta )* lambda  + a^2*TT*((koff/kon) + TT)*(gpp + ...
                          YT* Delta )* lambda ^2)* mu )^2)) - a* lambda *...
                   mu *(-(gpm*gym*YT* Delta * lambda *(YT* Delta *...
                       (gyp + a*(koff/kon)* lambda ) + gpp*(gym + gyp + a*(koff/kon)*...
                          lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )*...
                    (gpp*(gym + gyp + a*TT* lambda )*(gym + gyp + ...
                       a*((koff/kon) + TT)* lambda ) + YT* Delta *(gym*(gyp + ...
                         a*(koff/kon)* lambda ) + (gyp + a*TT* lambda )*(gyp + ...
                         a*((koff/kon) + TT)* lambda )))* mu ))/(a^2*(gpp + ...
                  YT* Delta )* lambda ^2* mu *(-(gpm*gym*YT* Delta *...
                     lambda ) + gpp*(gym + gyp + a*TT* lambda )^2* mu  + ...
                  YT* Delta *(gym*gyp + (gyp + a*TT* lambda )^2)* mu )))^...
              2)))/2) + (gym + gyp + ...
        (a* lambda *((koff/kon) + TT + (sqrt(-(a^2*gym*YT* Delta * lambda ^2* mu *...
                (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)*...
                   mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta *...
                    lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT*...
                        Delta ) + 2*a*TT*(gpp*(gym + gyp) + gyp*YT* Delta )*...
                      lambda  + a^2*TT*((koff/kon) + TT)*(gpp + YT* Delta )*...
                      lambda ^2)* mu )^2)) - a* lambda * mu *...
              (-(gpm*gym*YT* Delta * lambda *(YT* Delta *(gyp + ...
                    a*(koff/kon)* lambda ) + gpp*(gym + gyp + a*(koff/kon)* lambda ))) + ...
               (gpp*(gym + gyp) + gyp*YT* Delta )*(gpp*(gym + gyp + ...
                   a*TT* lambda )*(gym + gyp + a*((koff/kon) + TT)* lambda ) + ...
                 YT* Delta *(gym*(gyp + a*(koff/kon)* lambda ) + ...
                   (gyp + a*TT* lambda )*(gyp + a*((koff/kon) + TT)* lambda )))*...
                 mu ))/(a^2*(gpp + YT* Delta )* lambda ^2* mu *...
             (-(gpm*gym*YT* Delta * lambda ) + gpp*(gym + gyp + ...
                 a*TT* lambda )^2* mu  + YT* Delta *(gym*gyp + ...
                (gyp + a*TT* lambda )^2)* mu )) - ...
           sqrt((-4*TT*(sqrt(-(a^2*gym*YT* Delta * lambda ^2* mu *...
                   (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)*...
                      mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta *...
                       lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT*...
                           Delta ) + 2*a*TT*(gpp*(gym + gyp) + gyp*YT*...
                           Delta )* lambda  + a^2*TT*((koff/kon) + TT)*(gpp + ...
                         YT* Delta )* lambda ^2)* mu )^2)) - a* lambda *...
                  mu *(-(gpm*gym*YT* Delta * lambda *(YT* Delta *...
                      (gyp + a*(koff/kon)* lambda ) + gpp*(gym + gyp + a*(koff/kon)*...
                         lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )*...
                   (gpp*(gym + gyp + a*TT* lambda )*(gym + gyp + a*((koff/kon) + TT)*...
                        lambda ) + YT* Delta *(gym*(gyp + a*(koff/kon)* lambda ) + ...
                      (gyp + a*TT* lambda )*(gyp + a*((koff/kon) + TT)* lambda )))*...
                    mu )))/(a^2*(gpp + YT* Delta )* lambda ^2* mu *(...
                -(gpm*gym*YT* Delta * lambda ) + gpp*(gym + gyp + ...
                   a*TT* lambda )^2* mu  + YT* Delta *(gym*gyp + ...
                  (gyp + a*TT* lambda )^2)* mu )) + ...
             ((koff/kon) + TT + (sqrt(-(a^2*gym*YT* Delta * lambda ^2* mu *...
                    (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)*...
                       mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta *...
                        lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT*...
                           Delta ) + 2*a*TT*(gpp*(gym + gyp) + gyp*YT*...
                           Delta )* lambda  + a^2*TT*((koff/kon) + TT)*(gpp + ...
                          YT* Delta )* lambda ^2)* mu )^2)) - a* lambda *...
                   mu *(-(gpm*gym*YT* Delta * lambda *(YT* Delta *...
                       (gyp + a*(koff/kon)* lambda ) + gpp*(gym + gyp + a*(koff/kon)*...
                          lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )*...
                    (gpp*(gym + gyp + a*TT* lambda )*(gym + gyp + ...
                       a*((koff/kon) + TT)* lambda ) + YT* Delta *(gym*(gyp + ...
                         a*(koff/kon)* lambda ) + (gyp + a*TT* lambda )*(gyp + ...
                         a*((koff/kon) + TT)* lambda )))* mu ))/(a^2*(gpp + ...
                  YT* Delta )* lambda ^2* mu *(-(gpm*gym*YT* Delta *...
                     lambda ) + gpp*(gym + gyp + a*TT* lambda )^2* mu  + ...
                  YT* Delta *(gym*gyp + (gyp + a*TT* lambda )^2)* mu )))^...
              2)))/2)*(gpm + gpp + ...
        (a* mu *((koff/kon) + TT + (sqrt(-(a^2*gym*YT* Delta * lambda ^2* mu *...
                (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)*...
                   mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta *...
                    lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT*...
                        Delta ) + 2*a*TT*(gpp*(gym + gyp) + gyp*YT* Delta )*...
                      lambda  + a^2*TT*((koff/kon) + TT)*(gpp + YT* Delta )*...
                      lambda ^2)* mu )^2)) - a* lambda * mu *...
              (-(gpm*gym*YT* Delta * lambda *(YT* Delta *(gyp + ...
                    a*(koff/kon)* lambda ) + gpp*(gym + gyp + a*(koff/kon)* lambda ))) + ...
               (gpp*(gym + gyp) + gyp*YT* Delta )*(gpp*(gym + gyp + ...
                   a*TT* lambda )*(gym + gyp + a*((koff/kon) + TT)* lambda ) + ...
                 YT* Delta *(gym*(gyp + a*(koff/kon)* lambda ) + ...
                   (gyp + a*TT* lambda )*(gyp + a*((koff/kon) + TT)* lambda )))*...
                 mu ))/(a^2*(gpp + YT* Delta )* lambda ^2* mu *...
             (-(gpm*gym*YT* Delta * lambda ) + gpp*(gym + gyp + ...
                 a*TT* lambda )^2* mu  + YT* Delta *(gym*gyp + ...
                (gyp + a*TT* lambda )^2)* mu )) - ...
           sqrt((-4*TT*(sqrt(-(a^2*gym*YT* Delta * lambda ^2* mu *...
                   (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)*...
                      mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta *...
                       lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT*...
                           Delta ) + 2*a*TT*(gpp*(gym + gyp) + gyp*YT*...
                           Delta )* lambda  + a^2*TT*((koff/kon) + TT)*(gpp + ...
                         YT* Delta )* lambda ^2)* mu )^2)) - a* lambda *...
                  mu *(-(gpm*gym*YT* Delta * lambda *(YT* Delta *...
                      (gyp + a*(koff/kon)* lambda ) + gpp*(gym + gyp + a*(koff/kon)*...
                         lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )*...
                   (gpp*(gym + gyp + a*TT* lambda )*(gym + gyp + a*((koff/kon) + TT)*...
                        lambda ) + YT* Delta *(gym*(gyp + a*(koff/kon)* lambda ) + ...
                      (gyp + a*TT* lambda )*(gyp + a*((koff/kon) + TT)* lambda )))*...
                    mu )))/(a^2*(gpp + YT* Delta )* lambda ^2* mu *(...
                -(gpm*gym*YT* Delta * lambda ) + gpp*(gym + gyp + ...
                   a*TT* lambda )^2* mu  + YT* Delta *(gym*gyp + ...
                  (gyp + a*TT* lambda )^2)* mu )) + ...
             ((koff/kon) + TT + (sqrt(-(a^2*gym*YT* Delta * lambda ^2* mu *...
                    (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)*...
                       mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta *...
                        lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT*...
                           Delta ) + 2*a*TT*(gpp*(gym + gyp) + gyp*YT*...
                           Delta )* lambda  + a^2*TT*((koff/kon) + TT)*(gpp + ...
                          YT* Delta )* lambda ^2)* mu )^2)) - a* lambda *...
                   mu *(-(gpm*gym*YT* Delta * lambda *(YT* Delta *...
                       (gyp + a*(koff/kon)* lambda ) + gpp*(gym + gyp + a*(koff/kon)*...
                          lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )*...
                    (gpp*(gym + gyp + a*TT* lambda )*(gym + gyp + ...
                       a*((koff/kon) + TT)* lambda ) + YT* Delta *(gym*(gyp + ...
                         a*(koff/kon)* lambda ) + (gyp + a*TT* lambda )*(gyp + ...
                         a*((koff/kon) + TT)* lambda )))* mu ))/(a^2*(gpp + ...
                  YT* Delta )* lambda ^2* mu *(-(gpm*gym*YT* Delta *...
                     lambda ) + gpp*(gym + gyp + a*TT* lambda )^2* mu  + ...
                  YT* Delta *(gym*gyp + (gyp + a*TT* lambda )^2)* mu )))^...
              2)))/2));
