Emax = ...
    (PT*(YT* Delta *(gyp + (((koff / (koff + phi)) * psi^5)* lambda *((koff/kon) + TT + ...
            (sqrt(-(((koff / (koff + phi)) * psi^5)^2*gym*YT* Delta * lambda ^2* mu * ...
                 (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)* ...
                    mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta * ...
                     lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT* ...
                         Delta ) + 2*((koff / (koff + phi)) * psi^5)*TT*(gpp*(gym + gyp) + gyp*YT* ...
                         Delta )* lambda  + ((koff / (koff + phi)) * psi^5)^2*TT*((koff/kon) + TT)*(gpp + ...
                       YT* Delta )* lambda ^2)* mu )^2)) - ...
              ((koff / (koff + phi)) * psi^5)* lambda * mu *(-(gpm*gym*YT* Delta * lambda * ...
                  (YT* Delta *(gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + gpp*(gym + gyp + ...
                     ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )* ...
                 (gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gym + gyp + ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* ...
                      lambda ) + YT* Delta *(gym*(gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + ...
                    (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gyp + ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda )))*...
                  mu ))/(((koff / (koff + phi)) * psi^5)^2*(gpp + YT* Delta )* lambda ^2* mu *...
              (-(gpm*gym*YT* Delta * lambda ) + gpp*(gym + gyp + ...
                  ((koff / (koff + phi)) * psi^5)*TT* lambda )^2* mu  + YT* Delta *(gym*gyp + ...
                 (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2)* mu )) - ...
            sqrt((-4*TT*(sqrt(-(((koff / (koff + phi)) * psi^5)^2*gym*YT* Delta * lambda ^2* mu * ...
                    (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)* ...
                       mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta * ...
                        lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT* ...
                           Delta ) + 2*((koff / (koff + phi)) * psi^5)*TT*(gpp*(gym + gyp) + gyp*YT* ...
                           Delta )* lambda  + ((koff / (koff + phi)) * psi^5)^2*TT*((koff/kon) + TT)*(gpp + ...
                          YT* Delta )* lambda ^2)* mu )^2)) - ((koff / (koff + phi)) * psi^5)* lambda * ...
                   mu *(-(gpm*gym*YT* Delta * lambda *(YT* Delta * ...
                       (gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* ...
                          lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )* ...
                    (gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gym + gyp + ... 
                       ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda ) + YT* Delta *(gym*(gyp + ...
                         ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gyp + ...
                         ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda )))* mu )))/(((koff / (koff + phi)) * psi^5)^2* ...
                (gpp + YT* Delta )* lambda ^2* mu *(-(gpm*gym*YT* Delta * ...
                    lambda ) + gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2* mu  + ...
                 YT* Delta *(gym*gyp + (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2)* mu )) +  ...
              ((koff/kon) + TT + (sqrt(-(((koff / (koff + phi)) * psi^5)^2*gym*YT* Delta * lambda ^2* mu * ...
                     (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)* ...
                        mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta * ...
                         lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT* ...
                           Delta ) + 2*((koff / (koff + phi)) * psi^5)*TT*(gpp*(gym + gyp) + gyp*YT* ...
                           Delta )* lambda  + ((koff / (koff + phi)) * psi^5)^2*TT*((koff/kon) + TT)*(gpp +  ...
                          YT* Delta )* lambda ^2)* mu )^2)) - ((koff / (koff + phi)) * psi^5)* lambda * ...
                    mu *(-(gpm*gym*YT* Delta * lambda *(YT* Delta * ...
                        (gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* ...
                           lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )* ...
                     (gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gym + gyp + ...
                        ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda ) + YT* Delta *(gym*(gyp + ...
                          ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gyp + ...
                          ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda )))* mu ))/(((koff / (koff + phi)) * psi^5)^2*(gpp + ...
                   YT* Delta )* lambda ^2* mu *(-(gpm*gym*YT* Delta *...
                      lambda ) + gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2* mu  + ... 
                   YT* Delta *(gym*gyp + (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2)* mu )))^ ...
               2)))/2) + gpp*(gym + gyp + ...
         (((koff / (koff + phi)) * psi^5)* lambda *((koff/kon) + TT + (sqrt(-(((koff / (koff + phi)) * psi^5)^2*gym*YT* Delta * lambda ^2* ...
                  mu *(-(gpm*(gpp + YT* Delta )* lambda ) + ...
                  gpp*(gym + gyp)* mu  + gyp*YT* Delta * mu )* ...
                 (gpm*gym*YT* Delta * lambda  - ((gym + gyp)* ...
                      (gpp*(gym + gyp) + gyp*YT* Delta ) + 2*((koff / (koff + phi)) * psi^5)*TT* ...
                      (gpp*(gym + gyp) + gyp*YT* Delta )* lambda  + ...
                     ((koff / (koff + phi)) * psi^5)^2*TT*((koff/kon) + TT)*(gpp + YT* Delta )* lambda ^2)* mu )^...
                  2)) - ((koff / (koff + phi)) * psi^5)* lambda * mu *(-(gpm*gym*YT* Delta * lambda *...
                  (YT* Delta *(gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + gpp*(gym + gyp + ...
                     ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )*...
                 (gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gym + gyp + ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)*...
                      lambda ) + YT* Delta *(gym*(gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + ...
                    (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gyp + ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda )))*...
                  mu ))/(((koff / (koff + phi)) * psi^5)^2*(gpp + YT* Delta )* lambda ^2* mu * ...
              (-(gpm*gym*YT* Delta * lambda ) + gpp*(gym + gyp + ...
                  ((koff / (koff + phi)) * psi^5)*TT* lambda )^2* mu  + YT* Delta *(gym*gyp + ...
                 (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2)* mu )) - ...
            sqrt((-4*TT*(sqrt(-(((koff / (koff + phi)) * psi^5)^2*gym*YT* Delta * lambda ^2* mu * ...
                    (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)* ...
                       mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta * ...
                        lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT* ...
                           Delta ) + 2*((koff / (koff + phi)) * psi^5)*TT*(gpp*(gym + gyp) + gyp*YT* ...
                           Delta )* lambda  + ((koff / (koff + phi)) * psi^5)^2*TT*((koff/kon) + TT)*(gpp + ...
                          YT* Delta )* lambda ^2)* mu )^2)) - ((koff / (koff + phi)) * psi^5)* lambda * ...
                   mu *(-(gpm*gym*YT* Delta * lambda *(YT* Delta * ...
                       (gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)*...
                          lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )*...
                    (gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gym + gyp + ...
                       ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda ) + YT* Delta *(gym*(gyp + ...
                         ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gyp + ...
                         ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda )))* mu )))/(((koff / (koff + phi)) * psi^5)^2*...
                (gpp + YT* Delta )* lambda ^2* mu *(-(gpm*gym*YT* Delta *...
                    lambda ) + gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2* mu  + ...
                 YT* Delta *(gym*gyp + (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2)* mu )) + ...
              ((koff/kon) + TT + (sqrt(-(((koff / (koff + phi)) * psi^5)^2*gym*YT* Delta * lambda ^2* mu *...
                     (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)*...
                        mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta *...
                         lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT*...
                           Delta ) + 2*((koff / (koff + phi)) * psi^5)*TT*(gpp*(gym + gyp) + gyp*YT*...
                           Delta )* lambda  + ((koff / (koff + phi)) * psi^5)^2*TT*((koff/kon) + TT)*(gpp + ...
                          YT* Delta )* lambda ^2)* mu )^2)) - ((koff / (koff + phi)) * psi^5)* lambda *...
                    mu *(-(gpm*gym*YT* Delta * lambda *(YT* Delta *...
                        (gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)*...
                           lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )*...
                     (gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gym + gyp + ...
                        ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda ) + YT* Delta *(gym*(gyp + ...
                          ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gyp + ...
                          ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda )))* mu ))/(((koff / (koff + phi)) * psi^5)^2*(gpp + ...
                   YT* Delta )* lambda ^2* mu *(-(gpm*gym*YT* Delta *...
                      lambda ) + gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2* mu  + ...
                   YT* Delta *(gym*gyp + (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2)* mu )))^...
               2)))/2)))/...
     (YT* Delta *(gyp + (((koff / (koff + phi)) * psi^5)* lambda *((koff/kon) + TT + ...
           (sqrt(-(((koff / (koff + phi)) * psi^5)^2*gym*YT* Delta * lambda ^2* mu * ...
                (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)*...
                   mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta *...
                    lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT*...
                        Delta ) + 2*((koff / (koff + phi)) * psi^5)*TT*(gpp*(gym + gyp) + gyp*YT* Delta )*...
                      lambda  + ((koff / (koff + phi)) * psi^5)^2*TT*((koff/kon) + TT)*(gpp + YT* Delta )*...
                      lambda ^2)* mu )^2)) - ((koff / (koff + phi)) * psi^5)* lambda * mu *...
              (-(gpm*gym*YT* Delta * lambda *(YT* Delta *(gyp + ...
                    ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ))) + ...
               (gpp*(gym + gyp) + gyp*YT* Delta )*(gpp*(gym + gyp + ...
                   ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gym + gyp + ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda ) + ...
                 YT* Delta *(gym*(gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + ...
                   (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gyp + ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda )))*...
                 mu ))/(((koff / (koff + phi)) * psi^5)^2*(gpp + YT* Delta )* lambda ^2* mu *...
             (-(gpm*gym*YT* Delta * lambda ) + gpp*(gym + gyp + ...
                 ((koff / (koff + phi)) * psi^5)*TT* lambda )^2* mu  + YT* Delta *(gym*gyp + ...
                (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2)* mu )) -... 
           sqrt((-4*TT*(sqrt(-(((koff / (koff + phi)) * psi^5)^2*gym*YT* Delta * lambda ^2* mu *...
                   (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)*...
                      mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta *...
                       lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT*...
                           Delta ) + 2*((koff / (koff + phi)) * psi^5)*TT*(gpp*(gym + gyp) + gyp*YT*...
                           Delta )* lambda  + ((koff / (koff + phi)) * psi^5)^2*TT*((koff/kon) + TT)*(gpp + ...
                         YT* Delta )* lambda ^2)* mu )^2)) - ((koff / (koff + phi)) * psi^5)* lambda *...
                  mu *(-(gpm*gym*YT* Delta * lambda *(YT* Delta *...
                      (gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)*...
                         lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )*...
                   (gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gym + gyp + ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)*...
                        lambda ) + YT* Delta *(gym*(gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + ...
                      (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gyp + ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda )))*...
                    mu )))/(((koff / (koff + phi)) * psi^5)^2*(gpp + YT* Delta )* lambda ^2* mu *(...
                -(gpm*gym*YT* Delta * lambda ) + gpp*(gym + gyp + ...
                   ((koff / (koff + phi)) * psi^5)*TT* lambda )^2* mu  + YT* Delta *(gym*gyp + ...
                  (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2)* mu )) + ...
             ((koff/kon) + TT + (sqrt(-(((koff / (koff + phi)) * psi^5)^2*gym*YT* Delta * lambda ^2* mu *...
                    (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)*...
                       mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta *...
                        lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT*...
                           Delta ) + 2*((koff / (koff + phi)) * psi^5)*TT*(gpp*(gym + gyp) + gyp*YT*...
                           Delta )* lambda  + ((koff / (koff + phi)) * psi^5)^2*TT*((koff/kon) + TT)*(gpp + ...
                          YT* Delta )* lambda ^2)* mu )^2)) - ((koff / (koff + phi)) * psi^5)* lambda *...
                   mu *(-(gpm*gym*YT* Delta * lambda *(YT* Delta *...
                       (gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)*...
                          lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )*...
                    (gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gym + gyp + ...
                       ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda ) + YT* Delta *(gym*(gyp + ...
                         ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gyp + ...
                         ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda )))* mu ))/(((koff / (koff + phi)) * psi^5)^2*(gpp + ...
                  YT* Delta )* lambda ^2* mu *(-(gpm*gym*YT* Delta *...
                     lambda ) + gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2* mu  + ...
                  YT* Delta *(gym*gyp + (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2)* mu )))^...
              2)))/2) + (gym + gyp + ...
        (((koff / (koff + phi)) * psi^5)* lambda *((koff/kon) + TT + (sqrt(-(((koff / (koff + phi)) * psi^5)^2*gym*YT* Delta * lambda ^2* mu *...
                (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)*...
                   mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta *...
                    lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT*...
                        Delta ) + 2*((koff / (koff + phi)) * psi^5)*TT*(gpp*(gym + gyp) + gyp*YT* Delta )*...
                      lambda  + ((koff / (koff + phi)) * psi^5)^2*TT*((koff/kon) + TT)*(gpp + YT* Delta )*...
                      lambda ^2)* mu )^2)) - ((koff / (koff + phi)) * psi^5)* lambda * mu *...
              (-(gpm*gym*YT* Delta * lambda *(YT* Delta *(gyp + ...
                    ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ))) + ...
               (gpp*(gym + gyp) + gyp*YT* Delta )*(gpp*(gym + gyp + ...
                   ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gym + gyp + ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda ) + ...
                 YT* Delta *(gym*(gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + ...
                   (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gyp + ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda )))*...
                 mu ))/(((koff / (koff + phi)) * psi^5)^2*(gpp + YT* Delta )* lambda ^2* mu *...
             (-(gpm*gym*YT* Delta * lambda ) + gpp*(gym + gyp + ...
                 ((koff / (koff + phi)) * psi^5)*TT* lambda )^2* mu  + YT* Delta *(gym*gyp + ...
                (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2)* mu )) - ...
           sqrt((-4*TT*(sqrt(-(((koff / (koff + phi)) * psi^5)^2*gym*YT* Delta * lambda ^2* mu *...
                   (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)*...
                      mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta *...
                       lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT*...
                           Delta ) + 2*((koff / (koff + phi)) * psi^5)*TT*(gpp*(gym + gyp) + gyp*YT*...
                           Delta )* lambda  + ((koff / (koff + phi)) * psi^5)^2*TT*((koff/kon) + TT)*(gpp + ...
                         YT* Delta )* lambda ^2)* mu )^2)) - ((koff / (koff + phi)) * psi^5)* lambda *...
                  mu *(-(gpm*gym*YT* Delta * lambda *(YT* Delta *...
                      (gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)*...
                         lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )*...
                   (gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gym + gyp + ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)*...
                        lambda ) + YT* Delta *(gym*(gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + ...
                      (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gyp + ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda )))*...
                    mu )))/(((koff / (koff + phi)) * psi^5)^2*(gpp + YT* Delta )* lambda ^2* mu *(...
                -(gpm*gym*YT* Delta * lambda ) + gpp*(gym + gyp + ...
                   ((koff / (koff + phi)) * psi^5)*TT* lambda )^2* mu  + YT* Delta *(gym*gyp + ...
                  (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2)* mu )) + ...
             ((koff/kon) + TT + (sqrt(-(((koff / (koff + phi)) * psi^5)^2*gym*YT* Delta * lambda ^2* mu *...
                    (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)*...
                       mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta *...
                        lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT*...
                           Delta ) + 2*((koff / (koff + phi)) * psi^5)*TT*(gpp*(gym + gyp) + gyp*YT*...
                           Delta )* lambda  + ((koff / (koff + phi)) * psi^5)^2*TT*((koff/kon) + TT)*(gpp + ...
                          YT* Delta )* lambda ^2)* mu )^2)) - ((koff / (koff + phi)) * psi^5)* lambda *...
                   mu *(-(gpm*gym*YT* Delta * lambda *(YT* Delta *...
                       (gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)*...
                          lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )*...
                    (gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gym + gyp + ...
                       ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda ) + YT* Delta *(gym*(gyp + ...
                         ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gyp + ...
                         ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda )))* mu ))/(((koff / (koff + phi)) * psi^5)^2*(gpp + ...
                  YT* Delta )* lambda ^2* mu *(-(gpm*gym*YT* Delta *...
                     lambda ) + gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2* mu  + ...
                  YT* Delta *(gym*gyp + (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2)* mu )))^...
              2)))/2)*(gpm + gpp + ...
        (((koff / (koff + phi)) * psi^5)* mu *((koff/kon) + TT + (sqrt(-(((koff / (koff + phi)) * psi^5)^2*gym*YT* Delta * lambda ^2* mu *...
                (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)*...
                   mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta *...
                    lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT*...
                        Delta ) + 2*((koff / (koff + phi)) * psi^5)*TT*(gpp*(gym + gyp) + gyp*YT* Delta )*...
                      lambda  + ((koff / (koff + phi)) * psi^5)^2*TT*((koff/kon) + TT)*(gpp + YT* Delta )*...
                      lambda ^2)* mu )^2)) - ((koff / (koff + phi)) * psi^5)* lambda * mu *...
              (-(gpm*gym*YT* Delta * lambda *(YT* Delta *(gyp + ...
                    ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ))) + ...
               (gpp*(gym + gyp) + gyp*YT* Delta )*(gpp*(gym + gyp + ...
                   ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gym + gyp + ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda ) + ...
                 YT* Delta *(gym*(gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + ...
                   (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gyp + ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda )))*...
                 mu ))/(((koff / (koff + phi)) * psi^5)^2*(gpp + YT* Delta )* lambda ^2* mu *...
             (-(gpm*gym*YT* Delta * lambda ) + gpp*(gym + gyp + ...
                 ((koff / (koff + phi)) * psi^5)*TT* lambda )^2* mu  + YT* Delta *(gym*gyp + ...
                (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2)* mu )) - ...
           sqrt((-4*TT*(sqrt(-(((koff / (koff + phi)) * psi^5)^2*gym*YT* Delta * lambda ^2* mu *...
                   (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)*...
                      mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta *...
                       lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT*...
                           Delta ) + 2*((koff / (koff + phi)) * psi^5)*TT*(gpp*(gym + gyp) + gyp*YT*...
                           Delta )* lambda  + ((koff / (koff + phi)) * psi^5)^2*TT*((koff/kon) + TT)*(gpp + ...
                         YT* Delta )* lambda ^2)* mu )^2)) - ((koff / (koff + phi)) * psi^5)* lambda *...
                  mu *(-(gpm*gym*YT* Delta * lambda *(YT* Delta *...
                      (gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)*...
                         lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )*...
                   (gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gym + gyp + ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)*...
                        lambda ) + YT* Delta *(gym*(gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + ...
                      (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gyp + ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda )))*...
                    mu )))/(((koff / (koff + phi)) * psi^5)^2*(gpp + YT* Delta )* lambda ^2* mu *(...
                -(gpm*gym*YT* Delta * lambda ) + gpp*(gym + gyp + ...
                   ((koff / (koff + phi)) * psi^5)*TT* lambda )^2* mu  + YT* Delta *(gym*gyp + ...
                  (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2)* mu )) + ...
             ((koff/kon) + TT + (sqrt(-(((koff / (koff + phi)) * psi^5)^2*gym*YT* Delta * lambda ^2* mu *...
                    (-(gpm*(gpp + YT* Delta )* lambda ) + gpp*(gym + gyp)*...
                       mu  + gyp*YT* Delta * mu )*(gpm*gym*YT* Delta *...
                        lambda  - ((gym + gyp)*(gpp*(gym + gyp) + gyp*YT*...
                           Delta ) + 2*((koff / (koff + phi)) * psi^5)*TT*(gpp*(gym + gyp) + gyp*YT*...
                           Delta )* lambda  + ((koff / (koff + phi)) * psi^5)^2*TT*((koff/kon) + TT)*(gpp + ...
                          YT* Delta )* lambda ^2)* mu )^2)) - ((koff / (koff + phi)) * psi^5)* lambda *...
                   mu *(-(gpm*gym*YT* Delta * lambda *(YT* Delta *...
                       (gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*(koff/kon)*...
                          lambda ))) + (gpp*(gym + gyp) + gyp*YT* Delta )*...
                    (gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gym + gyp + ...
                       ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda ) + YT* Delta *(gym*(gyp + ...
                         ((koff / (koff + phi)) * psi^5)*(koff/kon)* lambda ) + (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )*(gyp + ...
                         ((koff / (koff + phi)) * psi^5)*((koff/kon) + TT)* lambda )))* mu ))/(((koff / (koff + phi)) * psi^5)^2*(gpp + ...
                  YT* Delta )* lambda ^2* mu *(-(gpm*gym*YT* Delta *...
                     lambda ) + gpp*(gym + gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2* mu  + ...
                  YT* Delta *(gym*gyp + (gyp + ((koff / (koff + phi)) * psi^5)*TT* lambda )^2)* mu )))^...
              2)))/2));
